// build-data.mjs
// -----------------------------------------------------------------------------
// Orchestrates the data layer and writes the files the front-end reads.
//
//   node pipeline/build-data.mjs            # default: placeholder data
//   node pipeline/build-data.mjs --live     # use real fetchers (when wired up)
//
// Outputs two files into /data:
//   data/dataset.js    -> assigns window.LUMBER_DATA (loaded via <script>, so the
//                         dashboard works by simply double-clicking index.html,
//                         no local web server or CORS headaches).
//   data/dataset.json  -> same payload as plain JSON for any other consumer.
//
// The GitHub Actions workflow runs this monthly and commits the result, which is
// what makes the published dashboard "automatically update".
// -----------------------------------------------------------------------------

import { writeFileSync, mkdirSync, readFileSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';
import { generateDataset } from './generate-placeholder.mjs';
import { fetchLiveDataset } from './fetch/index.mjs';
import { fetchNews } from './fetch/news.mjs';
import { homebuilders } from './homebuilders.mjs';
import { stumpage } from './stumpage.mjs';
import { fetchMills } from './mills.mjs';
import { fetchFires } from './fires.mjs';

const __dirname = dirname(fileURLToPath(import.meta.url));
const OUT_DIR = resolve(__dirname, '..', 'data');

async function main() {
  const live = process.argv.includes('--live');
  let dataset;

  if (live) {
    console.log('[build-data] LIVE mode — pulling from real sources…');
    dataset = await fetchLiveDataset({ fallback: generateDataset });
  } else {
    console.log('[build-data] PLACEHOLDER mode — generating synthetic dataset…');
    dataset = generateDataset();
  }

  // News board is keyless, so refresh it on every build (placeholder or live).
  try {
    const news = await fetchNews();
    if (news) { dataset.industry.news = news; console.log(`[build-data] news: ${news.items.length} headlines`); }
  } catch (e) { console.warn('[build-data] news fetch failed:', e.message); }

  // Resilience: the scrape-based live sources (GAC region exports, EDGAR company
  // production/revenue) occasionally fail transiently in CI. Rather than let a
  // chart vanish, carry forward the last good value from the previously-committed
  // data (which persists in the repo via the commit-back).
  if (live) carryForwardLive(dataset);

  // Top-10 homebuilders snapshot (manually-compiled reference, not a live feed).
  dataset.homebuilders = homebuilders();

  // Canadian stumpage-by-region snapshot (manually-compiled, not a live feed).
  dataset.stumpage = stumpage();

  // Fire & sawmill map. Mills are keyless (BC live + curated producers); fires
  // need a free FIRMS key. Both carry forward from the last build on any failure
  // so the map never goes blank.
  let prev = null;
  const readPrev = () => {
    if (prev !== null) return prev;
    try { prev = JSON.parse(readFileSync(resolve(OUT_DIR, 'dataset.json'), 'utf8')); }
    catch { prev = {}; }
    return prev;
  };
  try {
    dataset.mills = await fetchMills();
    console.log(`[build-data] mills: ${dataset.mills.count} (${JSON.stringify(dataset.mills.byProvince)})`);
  } catch (e) {
    const p = readPrev();
    if (p.mills) { dataset.mills = p.mills; console.warn('[build-data] ⚠ mills fetch failed — carried forward'); }
    else console.warn('[build-data] mills fetch failed and no prior data:', e.message);
  }
  try {
    const fires = await fetchFires(process.env.FIRMS_KEY);
    if (fires) { dataset.fires = fires; console.log(`[build-data] fires: ${fires.count} detections (24h)`); }
    else {
      const p = readPrev();
      if (p.fires) { dataset.fires = p.fires; console.log('[build-data] fires: no key/data — carried forward last set'); }
      else console.log('[build-data] fires: skipped (set FIRMS_KEY to enable)');
    }
  } catch (e) {
    const p = readPrev();
    if (p.fires) { dataset.fires = p.fires; console.warn('[build-data] ⚠ fires fetch failed — carried forward'); }
    else console.warn('[build-data] fires fetch failed and no prior data:', e.message);
  }

  // Stamp the actual build date so the dashboard's "updated" reflects each run.
  dataset.meta = dataset.meta || {};
  dataset.meta.lastUpdated = new Date().toISOString().slice(0, 10);

  mkdirSync(OUT_DIR, { recursive: true });

  const json = JSON.stringify(dataset, null, 2);
  writeFileSync(resolve(OUT_DIR, 'dataset.json'), json, 'utf8');

  const banner =
    '/* AUTO-GENERATED by pipeline/build-data.mjs — do not edit by hand. */\n';
  const js = `${banner}window.LUMBER_DATA = ${json};\n`;
  writeFileSync(resolve(OUT_DIR, 'dataset.js'), js, 'utf8');

  const nCompanies = Object.keys(dataset.companies).length;
  console.log(`[build-data] wrote data/dataset.js and data/dataset.json`);
  console.log(`[build-data] companies=${nCompanies} dataThrough=${dataset.meta.dataThrough} placeholder=${dataset.meta.isPlaceholder}`);
}

// Restore expensive/flaky live sections from the previous build if they went
// missing this run (a transient scrape failure), so charts don't disappear.
function carryForwardLive(ds) {
  let prev;
  try { prev = JSON.parse(readFileSync(resolve(OUT_DIR, 'dataset.json'), 'utf8')); }
  catch { return; }   // no previous build to fall back to

  ds.meta.live = ds.meta.live || {};

  // Industry: Canada→US exports by region (GAC scrape — ~78 pages, flakiest source).
  if (!ds.industry.exportsByRegion && prev.industry && prev.industry.exportsByRegion) {
    ds.industry.exportsByRegion = prev.industry.exportsByRegion;
    ds.meta.live.regionExports = true;
    console.log('[build-data] ⚠ region-exports scrape failed — carried forward last good data');
  }

  // Housing (FRED, keyless but transiently flaky). If a live housing build drops
  // out, the demand-side charts (months-supply, new-home sales, active listings)
  // vanish entirely — they're live-only. Carry them + the core housing series
  // forward from the last good build so the charts never disappear.
  const pi = prev.industry || {}, di = ds.industry;
  for (const k of ['newHomeSupply', 'newHomeSales', 'activeListings']) {
    if (!di[k] && pi[k]) { di[k] = pi[k]; console.log(`[build-data] ⚠ ${k} missing — carried forward last good data`); }
  }
  if (!ds.meta.live.housing && prev.meta && prev.meta.live && prev.meta.live.housing) {
    if (pi.housingStarts) di.housingStarts = pi.housingStarts;
    if (pi.housingPermits) di.housingPermits = pi.housingPermits;
    ds.meta.live.housing = true;
    console.log('[build-data] ⚠ housing fetch failed — carried forward last good live housing');
  }

  // SARIMAX export forecast (written by the later forecast.py step). build-data
  // rebuilds exportsByRegion without it each run; seed it from the last good
  // forecast so that if forecast.py fails the card doesn't disappear (forecast.py
  // overwrites this with a fresh forecast when it succeeds).
  if (di.exportsByRegion && !di.exportsByRegion.forecast &&
      pi.exportsByRegion && pi.exportsByRegion.forecast) {
    di.exportsByRegion.forecast = pi.exportsByRegion.forecast;
    console.log('[build-data] ⚠ forecast missing — carried forward last good forecast (forecast.py will refresh)');
  }

  // Per-company: production & revenue parsed from EDGAR filings.
  for (const [id, co] of Object.entries(ds.companies || {})) {
    const pco = prev.companies && prev.companies[id];
    if (!pco || !pco.live) continue;
    for (const field of ['production', 'revenue']) {
      if (pco.live[field] && !(co.live && co.live[field])) {
        co[field] = pco[field];
        co.live = { ...(co.live || {}), [field]: true };
        console.log(`[build-data] ⚠ ${id} ${field} missing — carried forward last good data`);
      }
    }
  }
}

main().catch((err) => {
  console.error('[build-data] FAILED:', err);
  process.exit(1);
});
