#!/usr/bin/env python3
# lira.py — Harvard JCHS Leading Indicator of Remodeling Activity (LIRA).
# -----------------------------------------------------------------------------
# The gold-standard US home repair-and-remodel gauge: four-quarter moving total
# of homeowner improvement & repair spending ($B, annualized), WITH the JCHS
# model's 4-quarter-ahead projection. Runs AFTER build-data.mjs (like forecast.py)
# and writes industry.lira into the dataset.
#
# Source: the "Historical LIRA Benchmark Data …xlsx" published on the LIRA page
#   https://www.jchs.harvard.edu/research-areas/remodeling/lira
# The filename is versioned per release (…_2026_Q1.xlsx), so we scrape the page
# for the current link rather than hardcode it. JCHS 403s default bots, hence the
# browser User-Agent. Projected quarters are flagged "(p)" in the Date column.
#
# Robust by design: any failure leaves the dataset untouched and exits 0 (and
# build-data's carryForwardLive keeps the previous LIRA so the chart never drops).
#
#   python pipeline/lira.py
# -----------------------------------------------------------------------------
import json, sys, io, re, urllib.request
from pathlib import Path

UA = {'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 '
                    '(KHTML, like Gecko) Chrome/120.0 Safari/537.36'}
PAGE = 'https://www.jchs.harvard.edu/research-areas/remodeling/lira'
BASE = 'https://www.jchs.harvard.edu'

def main():
    import pandas as pd
    root = Path(__file__).resolve().parents[1]
    ds_path = root / 'data' / 'dataset.json'
    d = json.loads(ds_path.read_text(encoding='utf-8'))

    # 1. Find the current benchmark-data xlsx link on the LIRA page.
    html = urllib.request.urlopen(urllib.request.Request(PAGE, headers=UA), timeout=45).read().decode('utf-8', 'replace')
    m = re.search(r'href="([^"]*Historical%20LIRA%20Benchmark%20Data[^"]*\.xlsx)"', html)
    if not m:
        print('[lira] benchmark xlsx link not found on page'); return
    href = m.group(1)
    url = href if href.startswith('http') else BASE + href

    # 2. Download + parse the "Historical Benchmark Data" sheet.
    xls = urllib.request.urlopen(urllib.request.Request(url, headers=UA), timeout=60).read()
    df = pd.read_excel(io.BytesIO(xls), sheet_name='Historical Benchmark Data', header=1)
    df = df.iloc[:, :3]
    df.columns = ['date', 'total', 'roc']

    labels, values, proj, connect = [], [], [], None
    for _, r in df.iterrows():
        s = str(r['date']).strip()
        mm = re.match(r'(\d{4}):Q([1-4])', s)
        if not mm:
            continue
        try:
            val = float(r['total'])
        except (TypeError, ValueError):
            continue
        if val != val:            # NaN
            continue
        period = f'{mm.group(1)} Q{mm.group(2)}'
        try:
            yoy = round(float(r['roc']) * 100, 1)
        except (TypeError, ValueError):
            yoy = None
        if '(p)' in s:            # projected quarter
            proj.append({'period': period, 'mean': round(val, 1), 'yoy': yoy})
        else:                     # actual/benchmark quarter
            labels.append(period); values.append(round(val, 1)); connect = round(val, 1)

    if not labels:
        print('[lira] no rows parsed'); return

    rel = re.search(r'_(\d{4})_Q(\d)', href)
    as_of = f'{rel.group(1)} Q{rel.group(2)}' if rel else None

    d['industry']['lira'] = {
        'unit': '$ billions (annualized)',
        'freq': 'quarterly',
        'asOf': as_of,
        'source': 'Harvard JCHS — Leading Indicator of Remodeling Activity (LIRA)',
        'metric': '4-quarter moving total of homeowner improvement & repair spending',
        'actual': {'labels': labels, 'values': values},
        'projection': {'connect': connect, 'series': proj},
        'lastActual': {'period': labels[-1], 'value': values[-1]},
    }

    ds_path.write_text(json.dumps(d, indent=2), encoding='utf-8')
    js = '/* AUTO-GENERATED by pipeline/build-data.mjs — do not edit by hand. */\n' \
         + 'window.LUMBER_DATA = ' + json.dumps(d, indent=2) + ';\n'
    (root / 'data' / 'dataset.js').write_text(js, encoding='utf-8')
    ptxt = f' + {len(proj)} projected (to {proj[-1]["period"]}={proj[-1]["mean"]})' if proj else ''
    print(f'[lira] {len(labels)} actual quarters (to {labels[-1]}={values[-1]}){ptxt}')

if __name__ == '__main__':
    try:
        main()
    except Exception as e:
        print(f'[lira] skipped (non-fatal): {e}', file=sys.stderr)
        sys.exit(0)
